openapi: 3.0.1
info:
  title: Push Notification API
  version: 1.0.0
servers:
  - url: https://app-pushnotifdotnet.azurewebsites.net
paths:
  /meeting:
    post:
      summary: Send a meeting notification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                meetingId:
                  type: string
                  description: The ID of the meeting
                meetingTime:
                  type: string
                  format: date-time
                  description: The time of the meeting
              required:
                - meetingId
                - meetingTime
      responses:
        '200':
          description: Notification sent successfully
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Failed to send notification
          content:
            text/plain:
              schema:
                type: string
